### ISSUE TITLE
Support for custom labels/patterns by users

### ISSUE THREAD

**Issue by Cnordbo** [actions/labeler#117]
**Feature suggestion**: 
Using bots like dependabot or security advisory bots that automatically creates PRs with suggested fixes/updates, it would be nice to be able to ignore PRs from those users globally or per label. 

**Issue Example**: 
Dependabot issues a PR for an updated package. 

**Labeler**: 
Reports the PR as "Missing tests"

**Conclusion**: 
You don`t test your dependencies to see if they run OK. 
And so its safe to say that this label does not belong on this PR. 

**Workaround**:
Dont include the label if there is a change to package.json in the PR.

**Cons for workaround**: 
PRs that update/add/remove a package in their PR as a result of a change, will be able to not get flagged as missing tests.

**Comment by raisedadead** [comment]
Not sure if this is going to solve your use-case, but you should be able to ignore an actor with:

```yml
if: github.actor != 'github-actions[bot]'
```

or

```yml
if: github.actor != 'dependabot[bot]'
```

Conditionals can be used both at a step level or a job level.

**Comment by MaksimZhukov** [comment]
Hello everyone! Thank you for the feature request. 
You can use `!` character to negate the pattern. Please see the [documentation](https://github.com/actions/labeler#basic-examples) for more examples. 
I’m closing the issue. Feel free to contact us if you have any concerns.
