### ISSUE TITLE
Issue when share workflow within organization

### ISSUE THREAD

**Issue by Jasstkn** [actions/labeler#123]
Configuration file for labeler can't be copied if you use shared workflow within the organization.
Is there any way to put configuration inside the workflow?

**Comment by MaksimZhukov** [comment]
Hello @Jasstkn !
Here is statement from [Reusing workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) GitHub documentation article: 

> If you reuse a workflow from a different repository, any actions in the called workflow run as if they were part of the caller workflow. For example, if the called workflow uses actions/checkout, the action checks out the contents of the repository that hosts the caller workflow, not the called workflow.

According to the documentation, your configuration file has to be in the same repository as caller workflow. Alternatively, you can clone the repository with the called workflow using the [checkout](https://github.com/actions/checkout) action:
```yml
- uses: actions/checkout@v3
  with:
    repository: 'Repository name with owner. For example, actions/checkout'
```

Please see the [GitHub documentation](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) for more examples.

**Comment by MaksimZhukov** [comment]
I’m closing the issue. Please let us know if you have any questions.

**Comment by jtmullen** [comment]
Hi @MaksimZhukov I have this same issue and I am confused by this solution you propose:

> According to the documentation, your configuration file has to be in the same repository as caller workflow. Alternatively, you can clone the repository with the called workflow using the [checkout](https://github.com/actions/checkout) action

It appears this action it hard-coded to make a request to the caller repo to get the labeler configuration. How does checking out the called repo (where my shared configuration lives) solve this?

**Comment by lrstanley** [comment]
@jtmullen just FYI, https://github.com/actions/labeler/releases/tag/v4.3.0 / https://github.com/actions/labeler/pull/394 has added support for `configuration-path` to look at the local filesystem, before making the API call to the repo directly. This means you can clone the central repo down first, and directly reference it inside of the action.

Can see an example of how I'm accomplishing the same here (`.github` being the repo where I keep my config):

https://github.com/lrstanley/.github/blob/f163452238082e6c5af52edab262253cbaaaaf99/.github/workflows/triage.yml#L49-L66

**Comment by Jaycon80** [comment]
Hello
