### ISSUE TITLE
Can't apply multi-words labels

### ISSUE THREAD

**Issue by royt-via** [actions/labeler#124]
I have a label called "Code Review".
I want this label to be applied on all PRs.
I set my yml file to look like this (tried both **Code Review** and **"Code Review"**) -
```
"Code Review":
  - ./*
  - ./**/*

Frontend:
  - frontend/*
  - frontend/**/*

Backend:
  - backend/*
  - backend/**/*
```
other labels work fine, just **Code Review** is failing

**Comment by valentijnscholten** [comment]
Might be something else for example the glob starting with a dot. I have trouble with globs not working. Multiword labels are working fine for me, for example see #271

**Comment by MaksimZhukov** [comment]
Hello everyone!
This issue has been open for a year without any activity, so I'm going to close it as stale.
Please feel free to contact us if the issue is still relevant to you and we will reopen it.
Thanks!
