### ISSUE TITLE
Action does not match folders starting with dot (.)

### ISSUE THREAD

**Issue by ibratoev** [actions/labeler#135]
Actual:
* if I have a change in a folder `src/.deploy` and matcher for `src/**/*` it would not be matched.

Expected:
* folders starting with dot should be matched as well.

It seems the issue is related to how Minimatch works. See https://github.com/isaacs/minimatch/issues/30 . Consider passing `{dot: true}` by default.

**Comment by alfieyfc** [comment]
I'm just giving it a wild guess, would it be just to add that parameter to these two lines?

```ts
const matchers = globs.map(g => new Minimatch(g, {dot: true})); 
```

https://github.com/actions/labeler/blob/69990a6043bd2b78ec675ec775d8e1cb62204ff0/src/main.ts#L187
https://github.com/actions/labeler/blob/69990a6043bd2b78ec675ec775d8e1cb62204ff0/src/main.ts#L202

**Comment by mcieplucha** [comment]
actually I'm having issues event with root level configuration like:
`- ./*.js`
which seems to be not working. anyone did managed to make it work?

**Comment by lPaths** [comment]
been 5 months already, any update on this?

**Comment by boliveira** [comment]
How is the status of this?

**Comment by beefchimi** [comment]
Would also love to see a fix for this 🙏

**Comment by logicbomb421** [comment]
My company uses this action and is also encountering this issue. Seems like this is a pretty simple update, would it be possible to get this out soon?

**Comment by kachkaev** [comment]
Today we were [configuring labels](https://github.com/blockprotocol/blockprotocol/pull/191) in [blockprotocol/blockprotocol](https://github.com/blockprotocol/blockprotocol) and I was like ‘on no not this dot problem again’ 😅

So here is the fix: https://github.com/actions/labeler/pull/316. It is non-breaking, just allows us to set the `dot` parameter:

```diff
 name: "Pull Request Labeler"
 on:
 - pull_request_target

 jobs:
   triage:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/labeler@v3
       with:
         repo-token: "${{ secrets.GITHUB_TOKEN }}"
+        dot: true
```

I hope it will be available for everyone soon! 🤞

**Comment by kachkaev** [comment]
The solution to this confusing issue has been up for nearly 10 months: https://github.com/actions/labeler/pull/316 😔 Any chance we can get it merged before NY2023? 🤞

**Comment by MaksimZhukov** [comment]
Hello everyone! 
We have released a [new version](https://github.com/actions/labeler/releases/tag/v4.1.0) of the action with this feature on board.
Thank you for the patience!

**Comment by kachkaev** [comment]
![futurama-good-news-everyone](https://github.com/actions/labeler/assets/608862/fc651aac-c270-4027-b7fe-afad9de1f520)

The `dot` option is `true` by default in v5 🎉
Release notes: https://github.com/actions/labeler/releases/tag/v5.0.0
