### ISSUE TITLE
Remove labels for reverted changes

### ISSUE THREAD

**Issue by heshamMassoud** [actions/labeler#14]
Reproducing:

1. Change something in a file in some PR.
2. A label will be added to the PR that matches the location of the changed file.
3. Revert the changes on the changed file. (i.e. the PR does not contain changes in such file).
4. The label will still be there on the PR. But it should be removed, since the PR does not affect such file anymore.

**Comment by heshamMassoud** [comment]
Thanks for the reply @damccorm 

Regarding **point#1**, that is definitely a valid argument. Could be solved by only being able to remove labels which have been added by the same "labeler" bot and not by someone else. But I am not sure if github exposes such info (who added a certain label) 🤔

Regarding **point#2**, I am not sure I am with you on this one. Not having the label any more on some PR, simply means that the PR doesn't contain any changes categorised under such label (at least not anymore), which in turn, means that searching using a certain label should only result in PRs which affect codebase fulfilling such category, which is correct. If anything, then searching for such PR should be done with another query/filter.

**Comment by damccorm** [comment]
Yeah, I think I agree with your analysis of my second point, so I guess we're just left with the first one.

The more I think about this, the more I think we want it though. I guess if you really want to do what I'm describing you can create another label `documentation added (manual)` or something that doesn't appear in labeler.yml. It also just doesn't feel like the main use case. Maybe we flag it under an option or something so that we can turn it off.

Probably won't get to this immediately though, #12 feels a little more pressing to me.

**Comment by pzavolinsky** [comment]
> I'd like to see an option to choose the behaviour to update the labels created by the action somewhere in the pipeline definition.

Same here, I was planning on using labeler to add a `cr-no-tests` label to PRs that have no tests to ease the code review process (and I can think a couple more hints like these that would be super useful in prioritizing CR).

My initial config was this one:
```yml
cr-no-tests:
  - '!features/**/*.feature'
```

For these scenario I clearly want my `cr-no-tests` label to go away the moment a test appears.

We could get this going with:
- `const syncLables = !!core.getInput('sync-labels', {required: true});` [here](https://github.com/actions/labeler/blob/master/src/main.ts#L9)
- `else { labelsToRemove.push(label); }` [here](https://github.com/actions/labeler/blob/master/src/main.ts#L31)
- `if (syncLabels && labelsToRemove.length) { await removeLabels(client, prNumber, labelsToRemove); }` [here](https://github.com/actions/labeler/blob/master/src/main.ts#L37)

**Comment by kevinphelps** [comment]
I have opened pull request #63 which implements this issue (thanks for the pointers, @pzavolinsky).
