### ISSUE TITLE
Apply labels based on branch name

### ISSUE THREAD

**Issue by joshdales** [actions/labeler#186]
Hi there! At my work we usually include the type of work in our branch name eg. `feature/whatever-this-branch-does`.

Wondering if if would be possible to add the option to add labels based on the branch name as well as the files have changed?

Maybe something like this:
```yml
feature:
- branch: 'feature/*
```
to apply the `feature` label to a matching branch.

**Comment by androideveloper** [comment]
Something like this https://github.com/TimonVS/pr-labeler-action

**Comment by MaksimZhukov** [comment]
Hello everyone!
We released the new alpha version of the action that includes the implementation of this feature. For more information, see the [release notes](https://github.com/actions/labeler/releases/tag/v5.0.0-alpha.1). We would really appreciate it if you could try it out and provide us with [your feedback](issue-link). 

I will keep this issue open until the stable version is released.
Thank you!

**Comment by MaksimZhukov** [comment]
Hello everyone! 
We have released the [new major version of the action](https://github.com/actions/labeler/releases/tag/v5.0.0) with this feature on board. Thank you all for your patience!

@joshdales, thank you for implementing this feature! We really appreciate it!
