### ISSUE TITLE
Add "any file with ending..." to Readme

### ISSUE THREAD

**Issue by Twonki** [actions/labeler#24]
Hey there, 
love labeler. 

I would like to see something alike:

```
Java:
- ./**/*.java
``` 

For the Readme.

I think this is a nice usecase e.g. for Dockerfiles

**Comment by p942** [comment]
> Hey there,
> love labeler.
> 
> I would like to see something alike:
> 
> ```
> Java:
> - ./**/*.java
> ```
> 
> For the Readme.
> 
> I think this is a nice usecase e.g. for Dockerfiles

Hi na putanginanyo

**Comment by dbaileychess** [comment]
I don't think the updated docs added a good example that was cited in the original issue. I just want to add a label to any PR that touches a .java file, no matter where it is located in the repo. 

It is necessary to specify this: `./**/*.java` which is not that intuitive. It complains when you just do `**/*.java`. So adding this specific example would be useful.
