### ISSUE TITLE
multiple label and emoji support?

### ISSUE THREAD

**Issue by jhdcruz** [actions/labeler#27]
I have this certain label: `Reviewing :memo:`

If it is supported, can I ask on how to do it?

**Comment by NobbZ** [comment]
```yaml
"Reviewing :memo:": []
```

This seems to be valid YAML. Does this not work for you?

**Comment by jhdcruz** [comment]
> ```yaml
> "Reviewing :memo:": []
> ```
> 
> This seems to be valid YAML. Does this not work for you?

It does work for emoji, but somehow it doesn't apply multiple labels

Here's my `.github/labeler.yml`:
```yaml
"Reviewing :memo:":
  - src/*

"UI Design :art:":
  - src/pages/*
  - src/styles/**/*
```

Only `Reviewing :memo:` was applied, but the `UI Design :art:` wasn't applied;
the file I edited is in `src/pages/sample.html`.

**Comment by csi-lk** [comment]
Personally am using emoji in my labels by using the symbol not the shortcode eg.

```
💽 Package: packages/**/*
📦 Repo: ./*
```

**Comment by jhdcruz** [comment]
> 
> 
> Personally am using emoji in my labels by using the symbol not the shortcode eg.
> 
> `labeler.yml`
> 
> ```yaml
> 💽 Package: packages/**/*
> 📦 Repo: ./*
> ```

Unfortunately that doesn't work for me, @NobbZ solution works better for me. However only the first label is applied, and the other is skipped for some reason.

```yaml
"Reviewing :memo:":
  - src/*

"UI Design :art:":
  - src/pages/*
  - src/styles/**/*
```

Something I missed in the config? or only one label are allowed per folder?

**Comment by majman** [comment]
This is working on our repo:

```yml
🛸 Main:
- apps/main/**/*

🕹 Demo:
- apps/demo/**/*

💅 Style Guide:
- '@private-internal/**/*'
```

**Comment by NobbZ** [comment]
You have 3 distinct labels without overlapping pathes.

@jhdcruz seems to have problems with overlapping pathes though, not with the actual emojis…

----

> ```yaml
> "Reviewing :memo:":
>  - src/*
> ```

Only mathces the first level, your other label though matches some subdirectories. You probably want to do this:

```yaml
"Reviewing :memo:":
 - src/*
 - src/**/*
```

To match all files in the folder and all files in all subfolders of arbitrary depths.

**Comment by jhdcruz** [comment]
> 
> 
> You have 3 distinct labels without overlapping pathes.
> 
> @jhdcruz seems to have problems with overlapping pathes though, not with the actual emojis…
> 
> > ```yaml
> > "Reviewing :memo:":
> >  - src/*
> > ```
> 
> Only mathces the first level, your other label though matches some subdirectories. You probably want to do this:
> 
> ```yaml
> "Reviewing :memo:":
>  - src/*
>  - src/**/*
> ```
> 
> To match all files in the folder and all files in all subfolders of arbitrary depths.

I missed the paths. 😅

**Comment by PrafulAnand** [comment]
how can I add two separate labels for a change in a single file ?
