### ISSUE TITLE
labeler.yml example to match all repo files

### ISSUE THREAD

**Issue by lucascosti** [actions/labeler#28]
I'm trying to set up a rule to apply a `needs triage` label for _any_ file change in a repo, but I can't get it to work without manually specifying at least one folder in the path.

Here are some combinations I've tried without success:

```
needs triage:
  - '*'
```

```
needs triage:
  - '*'
  - '**/*'
```

```
needs triage:
  - ./*
  - ./**/*
```

```
needs triage:
  - '*'
```

It works for changes in a single folder if I provide at least part of a path, e.g.:

```
needs triage:
  - .github/*
```

Any help would be awesome!

**Comment by cpanato** [comment]
same for me

**Comment by azu** [comment]
similar issue? https://github.com/isaacs/minimatch/issues/30

**Comment by Alfalfamale** [comment]
This worked for me:
```yml
needs triage:
  - '**'      # index.php | src/main.php
  - '.*'      # .gitignore
  - '.*/**'   # .github/workflows/label.yml
```

the `./` at the start doesn't do anything for me, it doesn't work

**Comment by GMNGeoffrey** [comment]
Thanks I was trying to do the same thing and was confused why the "./*" syntax in the README wasn't working. It would be great if someone from the team addressed the broken documentation.

**Comment by MaksimZhukov** [comment]
Hello everyone! 
Thank you @Robvdhout  for the provided solution! 
The confusing syntax (`./`) has been removed from the README. 
I’m closing the issue. Please contact us if you have any concerns.
