### ISSUE TITLE
Fails on Forks

### ISSUE THREAD

**Issue by GregTheGreek** [actions/labeler#29]
It seems that when we have incoming pr's from a fork it fails to run.

See this [pr](https://github.com/ChainSafe/lodestar/pull/500)

**Comment by NobbZ** [comment]
Duplicate of #12.

**Comment by ethomson** [comment]
There's currently no workaround.  This is a dup of #12, where there's some discussion of some ideas.  I'm going to close this issue so that we can track that work in a single place.  Thanks for reporting this!
