### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by bryanmacfarlane** [actions/labeler#30]

**Comment by mgan59** [comment]
Was going to fix an issue, but realized there are no unit tests...  Feel like this should be a priority to address before any future fixes happen.  I see pr #34 has an example.  Is this desired pattern?  Or should an effort be made to separate out the various functions into a handful of like-functionality modules?

**Comment by pje** [comment]
@bryanmacfarlane & @mgan59: Fully agree! I got the ball rolling with #145, #148, and #149. Future PRs should be able to use the existing test/CI framework as a starting point.
