### ISSUE TITLE
Fails on forks

### ISSUE THREAD

**Issue by vandanaPGaallee** [actions/labeler#31]
Hello, 

 Most of the contributions is coming from the forked Repo, this action is not usable anymore since  it fails for the PR coming from the forked repo. 
Almost all the projects in my organisation are  using this action.  Is there any workaround or final solution to counter this issue ?.

**Comment by ethomson** [comment]
There's currently no workaround.  This is a dup of #12, where there's some discussion of some ideas.  I'm going to close this issue so that we can track that work in a single place.  Thanks for reporting this!
