### ISSUE TITLE
Issue with Labeler

### ISSUE THREAD

**Issue by logankilpatrick** [actions/labeler#32]
When I added the labeler to my repo, this is what I get: 

```yml
##[error]HttpError: Not Found
6
##[error]Not Found
7
##[error]Node run failed with exit code 1
```

**Comment by andymckay** [comment]
Thanks for the feedback @logankilpatrick. I've moved this issue over to the labeler repository @logankilpatrick since there's a specific repository devoted to this action.

**Comment by ethomson** [comment]
> That repo is so vague it's hard to understand.

Sorry @logankilpatrick, can you tell me what kind of problems you were having with the README?  We'd like to expand it to make it more clear and instructional.

**Comment by ethomson** [comment]
Oops!  I spoke too soon.  I now see #18, which is a very helpful report, indeed.  Thanks much for reporting this issue.  I'm going to close this one, and we'll track this in #18.
