### ISSUE TITLE
auto add label on the giver PR if ta test fails or not.

### ISSUE THREAD

**Issue by spolti** [actions/labeler#35]
Looks like there is not way to configure the labeler to auto set labes depending on the tests results
it can be a previous workflow or in the same one.

i.e. it is what I tried so far: 
create the labeler yaml file as described in the docs, plus add this step on my workflow:
`name: Java 8 CI

on: pull_request
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Maven
      run: mvn clean test --file pom.xml
    - if: success()
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml     
        ready: ./**/*`

where ready is the label name I expect to have it set.

The logs does not print anything useful.

**Comment by MaksimZhukov** [comment]
@spolti  please use the provided solution.
I’m closing the issue. Please let us know if you have any concerns.
