### ISSUE TITLE
Random syntax error when triggering the labeler with on.pull_request_target

### ISSUE THREAD

**Issue by jorgepiloto** [actions/labeler#360]
🐞 **Problem**

When using the `on.pull_request_target` option with `types: [opened, reopened]` arguments, GitHub actions complained about the syntax of the YML file, see the following log:

- Failing actions file: https://github.com/pyansys/pymapdl/actions/runs/2245457610/workflow

However, if replaced by the `on.pull_request` option, the syntax error is no longer reported. See the log:

- Passing actions file: https://github.com/pyansys/pymapdl/actions/runs/2245994855/workflow
 
The associated PR can be found in: https://github.com/pyansys/pymapdl/pull/1085

Any insights on which is the reason behind this behavior would be super useful.

**Comment by MaksimZhukov** [comment]
Hello @jorgepiloto!
I've forked the pymapdl repository and replaced the `pull_request` event with the `pull_request_target` event in the [label.yml](https://github.com/pyansys/pymapdl/blob/main/.github/workflows/label.yml) file like this:
```yml
pull_request_target:
    types: [opened, reopened]
```
Everything works without failures. It was probably a syntax error in your workflow.

**Comment by jorgepiloto** [comment]
Hi @MaksimZhukov, thanks a lot for working on this issue. Pinging here @germa89, as he is the main maintainer of the project.

We will apply these changes and, if we can reproduce, we can close this issue.

**Comment by MaksimZhukov** [comment]
@jorgepiloto, @germa89 have you had a chance to apply the changes?

**Comment by germa89** [comment]
Hi @MaksimZhukov 

It has been a long time and we did use the version without types.

I'm checking this again in: https://github.com/pyansys/pymapdl/pull/1683

**Comment by germa89** [comment]
It seems to work: https://github.com/pyansys/pymapdl/actions/runs/3675409378/jobs/6214787297

**Comment by MaksimZhukov** [comment]
Thank you!
In this case, I am closing the issue. Please contact us if you have any questions.
