### ISSUE TITLE
Labels are not being added to my PR

### ISSUE THREAD

**Issue by 1bberto** [actions/labeler#365]
I have the following configuration:

```.github/labeler.yml```
```
'labelA':
  - any: ['**/*.{sql,sqlproj}', '/DbSchema/SchemaMigrations/**', '/OS.DB/**']
    all: ['!/QA/**']
'labelB':
  - any: ['**/*.{config,cs,cshtml,csproj,sln,bat,cfg,dll,exe,ndproj,ps1,rb,sh}', 'Scripts/**/*', 'Utils/**/*', 'VSProjects/**/*', 'Rakefile', '.sonarlint/**', '.editorconfig', '.gitignore', '.gitattributes']
    all: ['!QA/**/*']
'labelC':
  - any: ['**/*.{css,html,js,sass,scss,ts,json}', 'WebSrc/**/*', '.eslintignore', '.sonarlint/**/*', 'husky/**/*', '.editorconfig', '.gitignore', '.gitattributes']
    all: ['!QA/**/*']
'labelD':
  - all: ['QA/**/*']
'labelE':
  - any: ['**/*.{yaml,yml}', '.github/**/*', 'helm/**/*']
```

for some reason the labels are not being added to the PR and are also being **removed** when I add the labels manually

**Comment by davidhunt135** [comment]
This appears to be cause by using 'any' and 'all'

This works for me:

`
label:
- 'glob'
- 'glob'
`

This doesn't

`
label:
- any: ['glob', 'glob']
`

**Comment by tn3rb** [comment]
from the readme:

> Unlike the top-level list, the list of path globs provided to any and all must ALL match against a path for the label to be applied.

my guess is that your rules are conflicting, 
ie: your rule for `labelA` can not satisfy both `'/DbSchema/SchemaMigrations/**'` and `'/OS.DB/**'` because a file can not exist in both of those folders at the same time. 

so in other words, you need to split those up, ie: what @davidhunt135 said

maybe try:
```
'labelA':
  - any: ['**/*.{sql,sqlproj}', '/DbSchema/SchemaMigrations/**']
    all: ['!/QA/**']
  - any: ['**/*.{sql,sqlproj}', '/OS.DB/**']
    all: ['!/QA/**']
```

**Comment by MaksimZhukov** [comment]
I’m closing the issue. Please let us know if you have any concerns.
