### ISSUE TITLE
Not able to run github actions labeler on self-hosted runner

### ISSUE THREAD

**Issue by polin924fbn** [actions/labeler#383]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

---------

I tried to run actions labeler on self-hosted runner by specifying `runs-on: self-hosted` in the yml file. But it is not working.
I am sure my self-hosted runner is connected to github.

For testing to run `labeler` in self-hosted runner, I created a branch and modified yml file from `runs-on: ubuntu-latest` to `runs-on: self-hosted` (master branch still uses `runs-on: ubuntu-latest`). But I still see `labeler` run on github hosted `ubuntu-latest` not on my self-hosted runner on the PR page. The question is does this `labeler` can only run on github hosted runner? or something wrongs here

thanks

**Comment by MaksimZhukov** [comment]
Hello @polin924fbn !
It seems to me that your workflow with labeler action uses master branch. Could you please check it?

**Comment by MaksimZhukov** [comment]
I’m closing the issue. Please let us know if you have any concerns.
