### ISSUE TITLE
Question: please clarify level of support given issue backlog length and PR backlog?

### ISSUE THREAD

**Issue by petemounce** [actions/labeler#395]
I'm trying to gauge whether to take a dependency on this action (which doesn't do _quite_ what I want; I want to define label configuration throughout the repo not just in a single place, since we monorepo), or whether to use `prow` (which comes with the drawback of hosting and maintaining it myself, obvs!) with its auto-labelling feature-set, or something else. I don't want to reinvent wheels.

At present, there are issues dating back to 2019 and PRs dating back to 2020. The most recent release was to bump a dependency. (I haven't looked hard and apologise if I have missed it therefore, but) there doesn't appear to be a lot of "product"-type activity.

What should expectations be around contributions, reviews and release cadence be, please?

I'm trying to figure out how well supported this action is before deciding what to do.

**Comment by dfandrich** [comment]
I just spent time creating a PR before discovering the backlog of 23 other PRs dating back 3 years. That doesn't bode well. I wouldn't have gone through the trouble if there's no chance of it ever seeing the light of day.

**Comment by dusan-trickovic** [comment]
Hello, @petemounce ! Thank you for reaching out! I just wanted to give you an update and let everyone know that the project has been transferred to the team. With that said, it should receive proper active support and maintainership going forward, so definitely be on the lookout. We apologize for the late response and appreciate your input (and interest) :)

**Comment by MaksimZhukov** [comment]
Hello everyone! 
We have been working on fixing bugs and implementing new features. We released a bunch of [action versions](https://github.com/actions/labeler/releases) with new features and bug fixes on board, and we are going to keep working on improving the action. 
I am closing this issue. Please let us know if you have any questions.
Thank you for your patience!
