### ISSUE TITLE
Bug: Similar glob combinations will cause no files to match

### ISSUE THREAD

**Issue by davidparsson** [actions/labeler#398]
When having a `labeler.yml` where patterns may be expanded to match similar file patterns, none of those will be matched.

Consider the following `labeler.yml`:

```
'some-label':
 - 'something*.txt'
 - 'something/**/*.txt'
```

Modifying `something_anything.txt` or `something/anything.txt` in a PR will **not** add the label, which I would expect. The Minimatch glob matcher ([labeler.ts#L203](https://github.com/actions/labeler/blob/ed55e8ab1fa323b4a53afb55132c065aa7a9f8f4/src/labeler.ts#L203)) will find multiple globs that both cannot be fulfilled. If this is expected I think clarifications in the documentation is needed.

The **workaround** I've found is to specify multiple `any` blocks:
```
'some-label':
 - any: ['something*.txt']
 - any: ['something/**/*.txt']
```

**Comment by MaksimZhukov** [comment]
Hello @davidparsson ! Thank you for reporting this.
I followed your instructions and could not reproduce the issue. Could you please provide us with a public repository where the issue occurs?

**Comment by davidparsson** [comment]
All right, I'll se if I can get one up and running.

**Comment by MaksimZhukov** [comment]
@davidparsson have you had a chance to prepare a public repository. Is this issue still relevant to you?

**Comment by MaksimZhukov** [comment]
I am closing the issue due to the lack of response.
Please provide us with the public repository and we will reopen the issue.
Thanks!
