### ISSUE TITLE
Label git submodule SHA updates not working 

### ISSUE THREAD

**Issue by crissuciu** [actions/labeler#437]
I want to label submodule's SHA updates

None of the following patterns is able to pickup the submodule-folder changes

`"Submodule": - any: ['submodule-folder/**/', 'submodule-folder', './submodule-folder/.', 'submodule-folder']`

**Comment by MaksimZhukov** [comment]
Hello @crissuciu !
The following pattern should work for git submodules:
```yml
'submodules':
 - 'submodule-folder'
```
Could you please confirm if it work for you?
If it does not work, please provide us with a link to the public repository where the issue occurs

**Comment by brianluckham** [comment]
yes, it is

**Comment by MaksimZhukov** [comment]
@crissuciu please use the provided pattern.
I’m closing the issue. Please let us know if you have any concerns.

**Comment by oerp-odoo** [comment]
@MaksimZhukov what if submodule is in sub directory? I tried label:

```yml
standard:
  - src/monodoo/odoo
  - src/extra/enterprise
```
And when change is: 

![Selection_268](https://user-images.githubusercontent.com/7812986/210978403-11525c43-8b38-4900-b83f-33848172a149.png)

No label is added.

NOTE. Pull request is created by github actions BOT. Not sure if its relevant with this issue.
