### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by Yikun** [actions/labeler#446]
```
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```

This error always happened since yesterday (before yesterday, it works for many years):

https://github.com/apache/spark/actions/runs/3200342170/jobs/5227121801
https://github.com/apache/spark/actions/runs/3200342170/jobs/5227121801

**Comment by tustvold** [comment]
Updating to v4.0.2 at least appears to fix this

**Comment by Yikun** [comment]
@tustvold Thanks, we also fixed by setting permission expectly

```
permission:
    content: read
    
```

**Comment by tustvold** [comment]
I spoke too soon, will try your fix :sweat_smile:

**Comment by MaksimZhukov** [comment]
Hello @Yikun ! 
Sorry for the late response!
It looks like you found out a solution. Can this issue be closed?

**Comment by Yikun** [comment]
@MaksimZhukov Yes, the issue had already resolved, but I'm still not sure it's a real problem or not, but it had real have behavior changes.

Maybe it should be closed by https://github.com/actions/labeler/pull/314, I guess?

**Comment by MaksimZhukov** [comment]
Here is the statement from the [GitHub documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job):
> The permissions for the GITHUB_TOKEN are initially set to the default setting for the enterprise, organization, or repository. If the default is set to the restricted permissions at any of these levels then this will apply to the relevant repositories. For example, if you choose the restricted default at the organization level then all repositories in that organization will use the restricted permissions as the default. The permissions are then adjusted based on any configuration within the workflow file, first at the workflow level and then at the job level.

I've created a workflow file without specifying the `permissions` key. Everything worked fine as long as my default permissions granted to `GITHUB_TOKEN` were permissive. It seems to me that your organization has restricted the default `GITHUB_TOKEN` permissions. 

Also, I would like to mention that it is recommended to specify the `permissions` key in workflow file to configure the minimum required permissions for a workflow or job. This section was also included in the example in the README file in scope of the PR you mentioned.

I am closing the issue. Please contact us if you have any concerns.

**Comment by Yikun** [comment]
@MaksimZhukov Thanks for your help and info!
