### ISSUE TITLE
How to exclude file by mask?

### ISSUE THREAD

**Issue by sungam3r** [actions/labeler#473]
Hi. I tried to exclude files by mask without luck in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1599. I don't want to write `test` label if only `*.approved.txt` files were changed.

Labeler config here https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/.github/labeler.yml#L3
Labeler CI here https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/.github/workflows/label.yml

In aforementioned PR bot placed both `kafka` (good) and `test` (not good) labels on PR.

**Comment by MaksimZhukov** [comment]
Hello @sungam3r !
You should use the following configuration so that the `test` tag is not added to your PR:
```yml
'test':
- any: ['test/**/*']
  all: ['!test/**/*.approved.txt']
```

**Comment by sungam3r** [comment]
Thanks. It works in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1610
