### ISSUE TITLE
Support for necessary files touched

### ISSUE THREAD

**Issue by tvdeyen** [actions/labeler#48]
It would be nice to have support for files/folders that need to be changed on a PR. The most prominent example would be tests.

Whenever a PR gets created that does not have touched files in `test/**/*` or `spec/**/*` or `**/*.spec/js` globs a label gets added.

```yaml
necessary:
  "Need Tests": spec/**/*
```

**Comment by MaksimZhukov** [comment]
Hello @tvdeyen !
It looks like the functionality you are looking for is already available. Have you tried this:
```yml
"Need Tests":
- any: ['**']
  all: ['!tests/**']
```

Please see the [documentation](https://github.com/actions/labeler#basic-examples) for more examples.

**Comment by MaksimZhukov** [comment]
@tvdeyen please use the provided solution. 
I’m closing the issue. Please let us know if you have any concerns.
