### ISSUE TITLE
Documentation: Describe how to label if _any_ file in the repository has changed or to _every_ PR

### ISSUE THREAD

**Issue by ejether** [actions/labeler#526]
**Description:**
I'm using Labeler to add a default label to _every_ opened PR. I've been unable to devise a set of globs that have reliably done what I needed.  I've tried a handful of things that did work sometimes but not on _every pr_. 

```yaml
norelease:
  - any: [ '**/*','.*/*','*' ]
```
```yaml
norelease:
  - './**/*'
  - './.*/*'
  - './*'
```
```yaml
norelease:
  - '**/*'
  - '.*/*'
  - '*'
```

I'd like to know what to do to label _every_ pr with a label

**Justification:**
I'm using the action to put a default label on every PR that affect downstream actions.  The user _could_ add the label manually and that's the work around but since in this repository, the label is always the same, I'd like to have it JustWork™ for my team. 

**Are you willing to submit a PR?**
Sure, if it comes to that

**Comment by panticmilos** [comment]
hi @ejether, thank you for the report, we will take a look at it :)

**Comment by MaksimZhukov** [comment]
Hello @ejether! 
We added examples to match all repo files in scope of this [pull request](https://github.com/actions/labeler/pull/600).
I am closing the issue. Please contact us if you have any questions.
