### ISSUE TITLE
Label PR based on base branch

### ISSUE THREAD

**Issue by hkdobrev** [actions/labeler#54]
Could the automatic labeler support more triggers than just the paths changed?

A very useful workflow for us would be set labels on the PR depending on the base branch of the PR. Depending on the Git branching workflow used in a project, this could have different use cases. For example, using the git-flow, a PR towards the development branch could be labeled as a feature and one towards master as a release.

If this feature request is implemented I imagine automatic labeling and its configuration could later be expanded to be based on branch patterns, author (if it's a robot for example) etc.

**Comment by XVilka** [comment]
Also related https://github.com/actions/labeler/issues/55 - probably implementing these will share some code.

**Comment by MaksimZhukov** [comment]
Hello everyone!
We released the new alpha version of the action that includes the implementation of this feature. For more information, see the [release notes](https://github.com/actions/labeler/releases/tag/v5.0.0-alpha.1). We would really appreciate it if you could try it out and provide us with [your feedback](https://github.com/actions/labeler/issues/575). 

I will keep this issue open until the stable version is released.
Thank you!

**Comment by MaksimZhukov** [comment]
Hello everyone! 
We have released the [new major version of the action](https://github.com/actions/labeler/releases/tag/v5.0.0) that includes the implementation of this feature. Please read the [action documentation](https://github.com/actions/labeler/tree/main#pull-request-labeler) to find out how to adapt your configuration files and workflows for use with the new action version.

Thank you all for your patience!
Do not hesitate to contact us if you have any questions!
