### ISSUE TITLE
HttpError: Server Error when using labeler with over 50 labels

### ISSUE THREAD

**Issue by jkinnula-elisa** [actions/labeler#561]
**Description:**
Do a labeler configuration in a mono-repo with over 50 components. The end result will be `HttpError: Server Error` due labeler posting labels update twice, on which first time succeeds - and second time fails.

GitHub has limit of max 100 labels on a Pull Request. On this case we are not talking about a mono-repo which has over 100 components (which would result 100 or over 100 labels), but a case that labeler does update the labels - and in the next update does post the labels again. GitHub does sanity check for addLabels - not to be able to exceed possible amount of new labels (e.g. if there's 51 labels already in PR, possible amount of new labels is 49). On this case the labels are actually the same, since labeler posted already the same labels before.

For short, this bug is about that error situation will happen in case that PR has more than 50 labels.

**Action version:**
v4.0.3

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [X] Self-hosted

**Repro steps:**  
- Create labeler configuration with 51 labels, merge the configuration into main/master
- Create a test PR which touches files enough to make 51 labels

**Expected behavior:**
No errors, and 51 labels are added.

**Actual behavior:**
Labels are added, but labeler workflow run failed due to error `HttpError: Server Error`.

**Comment by MaksimZhukov** [comment]
Hello @jkinnula-elisa ! 
Thank you for reporting this! We will investigate the issue
