### ISSUE TITLE
v5.0.0-alpha.1

### ISSUE THREAD

**Issue by MaksimZhukov** [actions/labeler#575]
We released the new alpha version of the action. It introduces the following major changes:
1) Fix the bug related to the `sync-labels` input. Now the input value is read correctly.
2) Add the ability to apply labels based on base and/or head branch names.
3) Change the behavior of the `any` selector to match ANY file against ANY glob pattern.

For more information, see the [release notes](https://github.com/actions/labeler/releases/tag/v5.0.0-alpha.1).

This is an alpha release and we would like to ask you to try it out and provide us with your feedback. If you have any questions, ideas or concerns, please share them in this issue.
Thank you!

**Comment by kachkaev** [comment]
How about setting [`dot` option](https://github.com/actions/labeler/pull/316) to `true` by default? I can craft a PR if this change is desired. From my personal experience, ‘special treatment’ of dot files by labeler is somewhat surprising.

**Comment by waiting-for-dev** [comment]
It looks that has been added on v4.1.0: https://github.com/actions/labeler/commit/82a4f6fc258f3df5a7b4e3ea7c4076397f45b7f2

**Comment by MaksimZhukov** [comment]
@kachkaev Thanks for the suggested idea! We will consider adding it to the new major release.

**Comment by lucacome** [comment]
@MaksimZhukov I've been using the alpha for the past moth in multiple repos and everything works as expected.
Any chance we can get a new alpha/beta with all the new features/updates that went into `main`? 🙏

**Comment by MaksimZhukov** [comment]
Thank you @lucacome for the feedback, we really appreciate it! 
We are considering the possibility of expanding the functionality of the alpha version. As soon as we finish the investigation, we will make appropriate changes, if necessary, and release a stable version. 
Thank you for your patience!

**Comment by jorgepiloto** [comment]
Hi @MaksimZhukov, I can confirm it fixes the issues with the ``sync-labels``. The fact that this version adds labels based on branch names, is an excellent feature. Thanks for all the effort and time you devoted to this action ❤️

**Comment by dfandrich** [comment]
There seems to be a different bug with `sync-labels` now. When not explicitly setting `sync-labels` in the GHA job file, the job errors out with
```
TypeError: Input does not meet YAML 1.2 "Core Schema" specification: sync-labels Support boolean input list: `true | True | TRUE | false | False | FALSE`
```
There needs to be an explicit `sync-labels: false` in the workflow file to avoid this; it can't be left out to rely on the default false value.

**Comment by MaksimZhukov** [comment]
@dfandrich, thank you for reporting this! Could you please create a new issue?

**Comment by joshdales** [comment]
Thanks for the updates in the new beta version - I was wondering why not use consistent casing for all the config keys names? eg. the new `changed-files` nested keys are all in PascalCase now rather than kebab-case. Would it not be better to have them all be the same?

I realise that some of this might be my fault as I added some of those keys 😅 I personally don't have a preference, I just went with kebab-case initially because it was the same as the action config, but if the nested changed file options are how y'all would rather future keys are then might make sense to switch `changed-files`, `head-branch`, `base-branch` as well?

**Comment by MaksimZhukov** [comment]
@joshdales, this is a great point, thank you. We will switch the nested options to kebab-case

**Comment by cwire4** [comment]
Have the outputs changed or gone away in the beta?  I originally used version 4 of the action and grabbed a snippet that outputs the new-labels and all-labels for the run.  When I switched to the beta version, this step no longer outputs any labels even if some were added.

This is the step I have in my yaml:

`    - name: "Check Outputs"
      run: |
        echo 'New labels:'
        echo '${{ steps.labeler.outputs.new-labels }}'
        echo '-------------------------'
        echo 'All labels:'
        echo '${{ steps.labeler.outputs.all-labels }}'`
        
The previous step's id is still labeler.

**Comment by dfandrich** [comment]
Some output like this would be welcome by default to help with debugging. Right
now, the logging of the action is rather…sparse.

**Comment by onesneakymofo** [comment]
Is there anyway someone can squeeze in #688 into the v5 release? We title our PRs with [FEATURE], [BUG], [CHORE], etc. and it would be nice to auto-label based off of that so we can automate our release notes. 🙏

**Comment by OJFord** [comment]
@MaksimZhukov May I second that `dot: true` by default would be good - afaict the only reason to add it default `false` was to avoid it being a breaking change, so why not break now with the v5? 

I can't think of any reason someone would want not to match dotfiles on path specs that do match them, it's not as if it's something weird & controversial like an 'implied dot' where '^foobar$' matches both 'foobar' and '.foobar'. It's just a random gotcha.

**Comment by MaksimZhukov** [comment]
Hello everyone! 
We have released the [new major version of the action](https://github.com/actions/labeler/releases/tag/v5.0.0). In the new version, `dot` input is set to `true` by default. It also contains a bunch of other important changes. Please read the [action documentation](https://github.com/actions/labeler/tree/main#pull-request-labeler) to find out how to adapt your configuration files and workflows for use with the new action version.

Thank you all for your feedback and patience! We really appreciate this! 
Do not hesitate to contact us if you have any questions!
