### ISSUE TITLE
A

### ISSUE THREAD

**Issue by Kongpc22** [actions/labeler#576]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by MaksimZhukov** [comment]
This issue is closed as spam
