### ISSUE TITLE
Question: Howto set a label if 2 files are changed within one PR

### ISSUE THREAD

**Issue by mcm1957** [actions/labeler#583]
Is there any way to set label if exactly 2 files are changed?

```
triage:
  - any: ["file1", "file2"]
```

will never triger as file1 and file2 never will match all paths.
But I cannot think of any construct using ! which will do this.

**Comment by dfandrich** [comment]
Take a look at #423 and PR#487 which I believe will do what you want.

**Comment by mcm1957** [comment]
Ok
Sounds like that current offical version cannot do this.

**Comment by MaksimZhukov** [comment]
Hello @mcm1957!
Unfortunately, this is not possible at the moment. I am closing this issue as a duplicate of https://github.com/actions/labeler/issues/423. Please track the feature progress in scope of that issue.
