### ISSUE TITLE
Removes label if someone applies it manually before the action runs

### ISSUE THREAD

**Issue by will-ockmore** [actions/labeler#584]
**Description:**
If someone manually labels a PR that would be labelled by the action before it completes, it removes the label.

**Action version:**
4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
1. Open a PR that changes files matching the labeler configuration
2. Manually apply the label that would be applied by the configuration
3. Labeler will remove the label

**Expected behavior:**
The action will do nothing if the label is already applied

**Actual behavior:**
The action removes the label

**Comment by MaksimZhukov** [comment]
Hello @will-ockmore ! Thank you for reporting this! 
We will investigate the issue!

**Comment by AndreiLobanovich** [comment]
Hey, @will-ockmore. 

Are you still having this issue? Is there anything I can help you with?

**Comment by alldayalone** [comment]
We faced the same issue
