### ISSUE TITLE
https://www.facebook.com/profile.php?id=100024424234304&mibextid=ZbWKwL

### ISSUE THREAD

**Issue by 280987659999** [actions/labeler#616]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dusan-trickovic** [comment]
Closing the issue as spam
