### ISSUE TITLE
labeler.yml file from local can not be accessed

### ISSUE THREAD

**Issue by ayushtkn** [actions/labeler#628]
**Description:**

If the yml file is not available in the main remote repo, it doesn't get fetched from local  PR branch

**Action version:**

All

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
[A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.](https://github.com/apache/hadoop/actions/runs/5630615215/job/15256787707?pr=5874)

**Expected behavior:**
It should pick the file available locally 

**Actual behavior:**
```
The configuration file (path: .github/labeler.yml) isn't not found locally, fetching via the api
```

**Comment by MaksimZhukov** [comment]
I am closing the issue. Please refer to the [action documentation](https://github.com/actions/labeler#using-configuration-path-input-together-with-the-actionscheckout-action) to fix the issue. 
Do not hesitate to contact us if you have any questions

**Comment by ayushtkn** [comment]
Thank you @MaksimZhukov.
Yes we needed the checkout functionality and post that it worked. Successfully working for Apache Hadoop :-)
