### ISSUE TITLE
Label not getting applied when changes are to files deeper than 4 levels

### ISSUE THREAD

**Issue by 317brian** [actions/labeler#652]
**Description:**

I have this path set in `labeler.yml`:

```yml
- "examples/quickstart/jupyter-notebooks/**"
```

`example` is a a directory at the root of the repo.

(And have tried multiple versions with additional `/**` tacked on at the end. I also tried pointing it at a specific file/directory)

Changes at the `examples/quickstart/jupyter-notebooks/` level will get auto labeled as `Area - Documentation`.

Anything below that, such as `examples/quickstart/jupyter-notebooks/notebooks` aren't getting autolabeled.

If I move a modified file from `/notebooks` up one level, the changes get picked up and autolabeled. 

**Action version:**

v4.3.0

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

Here's a link to a PR that tests all this: https://github.com/317brian/druid/pull/22

Repro step is to make a change to a file that's more than 4 levels deep in your repo.

**Expected behavior:**
I expect that changes in the child directories deeper than 4 levels get picked up properly and labeled.

**Actual behavior:**
No label gets applied.

**Comment by MaksimZhukov** [comment]
Hello @317brian!
Thank you for reporting this! 
We will investigate the issue and contact you as soon as we have any updates.

**Comment by MaksimZhukov** [comment]
Based on the debug logs, the action uses non-updated version of the configuration file
![image](https://github.com/actions/labeler/assets/46996400/99492900-e7a5-4e9b-a520-a5aa622dbadf)
You need to push the update of the `.github/labeler.yml` file to the `master` branch and it will fix the issue

**Comment by 317brian** [comment]
Oh, I didn't know that it picks up and uses the config in `master` and not the PR branch. 

Thanks!

**Comment by MaksimZhukov** [comment]
I am closing the issue. Feel free to let us know if you have any questions
