### ISSUE TITLE
A `only` filter

### ISSUE THREAD

**Issue by silverwind** [actions/labeler#670]
**Description:**
Support a syntax to set a label when ALL modified paths are all contained in the array.

```yaml
skip-changelog:
  - only: [CHANGELOG.md]
````

**Justification:**
This is useful in a few rare cases like for example when you have a changelog generator and don't want the changelog modification itself become part of the changelog. I'm sure there are more cases, but it's definitely not a common use case.

**Are you willing to submit a PR?**
no

**Comment by MaksimZhukov** [comment]
Hello @silverwind!
Thank you for the feature request!

Unfortunately, I don't quite understand how the `only` filter is supposed to work. Could you please explain its logic in more detail? 

Have you seen this [feature request](https://github.com/actions/labeler/issues/423). Is this what you are looking for?
