### ISSUE TITLE
sync-labels is (but shouldn't be) mandatory for jobs

### ISSUE THREAD

**Issue by dfandrich** [actions/labeler#686]
There seems to be a different bug with `sync-labels` in the [v5.0.0-beta.1](https://github.com/actions/labeler/releases/tag/v5.0.0-beta.1) release. When not explicitly setting `sync-labels` in the GHA job file, the job errors out with
```
TypeError: Input does not meet YAML 1.2 "Core Schema" specification: sync-labels Support boolean input list: `true | True | TRUE | false | False | FALSE`
```
There needs to be an explicit `sync-labels: false` in the workflow file to avoid this; it can't be left out to rely on the default false value.

_Originally posted by @dfandrich in https://github.com/actions/labeler/issues/575#issuecomment-1729100456_

**Comment by MaksimZhukov** [comment]
Hello @dfandrich!
I could not reproduce your issue, everything works without any error. Here is my [workflow file](https://github.com/MaksimZhukov/labeler-issue/actions/runs/6299179122/workflow) and [workflow run](https://github.com/MaksimZhukov/labeler-issue/actions/runs/6299179122/job/17099442485).
Could you please provide us with a link to the public repository where the issue occurs?

**Comment by MaksimZhukov** [comment]
I have forked the repository and have not encountered any problems: [workflow file](https://github.com/MaksimZhukov/curl/actions/runs/6312012505/workflow) and [workflow run](https://github.com/MaksimZhukov/curl/actions/runs/6312012505).

Could you please update your workflow and re-run the build? I think it should work.
By the way, the [dot input ](https://github.com/curl/curl/blob/master/.github/workflows/label.yml#L28) is not yet available in the beta version, unfortunately.

**Comment by dfandrich** [comment]
Strange—it now works when I remove it. I wonder what happened in those failing runs? I'll close this then.
