### ISSUE TITLE
Update default runtime to node20

### ISSUE THREAD

**Issue by benwells** [actions/labeler#689]
**Description:**

Node 16 has reached end of life on September 11, 2023.

https://github.com/actions/runner now supports node 20 as of [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) and we encourage teams to update their actions to run on node 20 runtime by default. 

[Changelog here](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

[Reference to previous PR when we migrated to node 16](https://github.com/actions/labeler/pull/319)
 
**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

**Comment by MaksimZhukov** [comment]
Thank you for creating the issue!

**Comment by MaksimZhukov** [comment]
The new action version was released: https://github.com/actions/labeler/releases/tag/v5.0.0
