### ISSUE TITLE
File limit right now defaults to 30

### ISSUE THREAD

**Issue by davazp** [actions/labeler#71]
I found actions/labeler is using `client.pulls.listFiles` which has a page size of 30 files.

This means that for bigger PRs this won't assign labels properly because it won't consider all files.  I get that there must be a limit because this could be very expensive otherwise. But the failure mode is surprising.

I would suggest increasing the page size to 100 (the limit of the Github API) and check if there are more files than a page, then it should emit a warning and not assign any label at all.

Thoughts?
Thanks!

**Comment by RasmusWL** [comment]
Fixed by https://github.com/actions/labeler/pull/96
