### ISSUE TITLE
Getting `sync-labels` type error after update to 5 version.

### ISSUE THREAD

**Issue by AlejandroFernandezLuces** [actions/labeler#728]
**Description:**
I'm getting the following error after updating to version 5 of the action: 

```
TypeError: Input does not meet YAML 1.2 "Core Schema" specification: sync-labels
Support boolean input list: true | True | TRUE | false | False | FALSE
```

I've set the parameter like this: `sync-labels: true`, so I think format should be fine. I think this bug was supposed to be fixed with the latest version, but I'm experiencing it with the latest one. 

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
This is the link to the PR that is facing the error: https://github.com/ansys/pyprimemesh/pull/685

Log of the action in case you can't see it:
```
Run actions/labeler@v5
  with:
    repo-token: ***
    configuration-path: .github/labeler.yml
    dot: true
Error: TypeError: Input does not meet YAML 1.[2](https://github.com/ansys/pyprimemesh/actions/runs/7260093332/job/19778557259?pr=685#step:2:2) "Core Schema" specification: sync-labels
Support boolean input list: `true | True | TRUE | false | False | FALSE`
Error: Input does not meet YAML 1.2 "Core Schema" specification: sync-labels
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

**Expected behavior:**
Normal function of the action
**Actual behavior:**
Getting the aforementioned error

**Comment by IvanZosimov** [comment]
Hi, @AlejandroFernandezLuces 👋 Thanks for the bug report, we will take a look!

**Comment by AlejandroFernandezLuces** [comment]
Most likely there was an bug on our side of the workflows, the action wasn't using the latest changes and it looked like a bug. Not closing to fully confirm that it was the cause of this bug. Will close this issue if this is the case or update you if not.

Thanks for the attention 🙂

**Comment by brianluckham** [comment]
gh pr checkout 685

**Comment by AlejandroFernandezLuces** [comment]
> Most likely there was an bug on our side of the workflows, the action wasn't using the latest changes and it looked like a bug. Not closing to fully confirm that it was the cause of this bug. Will close this issue if this is the case or update you if not.
> 
> Thanks for the attention 🙂

It was indeed our fault, closing this issue
