### ISSUE TITLE
any-glob-all-files does not working intuitevely

### ISSUE THREAD

**Issue by jnewb1** [actions/labeler#731]
there is currently no way to apply the "CI" label with the following rule

any-glob-all-files: [Jenkinsfile, .github/**]

when a PR which changes both Jenkinsfile and github actions files

open PR to fix: https://github.com/actions/labeler/pull/714

**Comment by IvanZosimov** [comment]
Hi, @jnewb1 👋 Thanks for the issue and PR, we will take a look.

**Comment by IvanZosimov** [comment]
Hi, @jnewb1, I believe that for your particular use case the glob's syntax of grouping conditions fits well. What I mean by that is:
```
any-glob-all-files: "{Jenkinsfile,.github/**}"
```
Could you, please, check that logic of this grouping is what you want to achieve and ping me back?

**Comment by jnewb1** [comment]
> Hi, @jnewb1, I believe that for your particular use case the glob's syntax of grouping conditions: `{a,b,c}` fits well. What I mean by that is:
> 
> ```
> 
> any-glob-all-files: "{Jenkinsfile,.github/**}"
> 
> ```
> 
> Could you, please, check that logic of this grouping is what you want to achieve and ping me back?

Thank you, this syntax works for my use case, though I think it is less readable

**Comment by dfandrich** [comment]
That that {} syntax documented anywhere? I couldn't find it. It's certainly not intuitive, and `any-glob-all-files` is still misnamed; it should be `one-glob-all-files`.
