### ISSUE TITLE
Broken reference link for `Creating A Workflow File` in README.

### ISSUE THREAD

**Issue by xames3** [actions/labeler#815]
**Description:**
Whilst reading through the documentation for more help, I stumbled upon this [link](https://help.github.com/en/articles/configuring-a-workflow#creating-a-workflow-file) which should apparently point to a reference article but seems the link is broken.

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows
- [x] Website

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted
- [x] Neither

**Repro steps:**  
Navigate through the README file and try to open the link which says `Creating A Workflow File`.

**Expected behavior:**
Ideally it should redirect the user to a valid article page.

**Actual behavior:**
Currently it redirects to a default page which shows that the article doesn't exist.

**Comment by aparnajyothi-y** [comment]
Hello @xames3, Thank you for creating this issue and we will get back to you once we have some feedback on this :)

**Comment by suyashgaonkar** [comment]
Hi @xames3 , Thank you for bringing this into our notice, we have updated the url in the README section of the documentation, You can now check the same in the official actions/labeler [docs](https://github.com/actions/labeler?tab=readme-ov-file).

**Comment by xames3** [comment]
@suyashgaonkar and @aparnajyothi-y, thanks for working out on this. should be fine to close the issue, I guess?
