### ISSUE TITLE
Need to rerun build and update main branch dist/index.js

### ISSUE THREAD

**Issue by taehwanno** [actions/labeler#94]
**Problem**

In #22, it was built based on @actions/core old version and merged into main. As a result, an error like #88 occurs.

**Solution**

We need to rerun build and update `main` branch dist/index.js with @actions/core `v1.2.4`

**Additional work to prevent recurrence**

It seems possible to add the steps below to prevent a recurrence.

1. Add `prebuild` script (`npm install`) for installing the latest dependencies in each developer's local machine. (#95)
2. Add branch protection rule to `main` branch (Enable "Require branches to be up to date before merging" in "Require status checks to pass before merging") -> maybe someone possible?

**Comment by dakale** [comment]
Should be fixed now, see https://github.com/actions/labeler/pull/95
